# -*- coding: utf-8 -*-
"""stable_diffusion_image_generation 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fARUr2qXCG09een3PYkApulUkpJ63O4x
"""

# Install required libraries
# Load Stable Diffusion model
pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
# Step 3: Import libraries and load Stable Diffusion model

from diffusers import StableDiffusionPipeline
import torch

# Load the Stable Diffusion model
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
)

# Move model to GPU
pipe = pipe.to("cuda")

# Step 4: Generate an image from a text prompt

prompt = "A beautiful sunset over mountains with a lake"

image = pipe(prompt).images[0]

# Show the image
image

# Step 5: Generate multiple images

prompt = "A futuristic city with flying cars at sunset"

images = pipe(prompt, num_images_per_prompt=3).images

# Display all generated images
for img in images:
    display(img)

# Step 6: Save the generated image

prompt = "A futuristic city with flying cars at sunset"

image = pipe(prompt).images[0]

# Save the image
image.save("generated_image.png")

# Display the image
image

prompt = input("Enter your image description: ")

image = pipe(prompt).images[0]

image

prompt = "A futuristic city with flying cars"

images = pipe(prompt, num_images_per_prompt=3).images

for img in images:
    display(img)

for i, img in enumerate(images):
    img.save(f"generated_image_{i}.png")

"""Example prompts:A futuristic city with flying cars
A dragon flying over mountains
A classical dancer performing on stage
A robot reading a book in a library

Stable Diffusion is a generative AI model that creates images from text prompts.
It starts with random noise and gradually removes noise to form a clear image
that matches the given text description.
"""

generator = torch.manual_seed(42)

image = pipe(prompt, generator=generator).images[0]

image